name: CI
on:
  push:
    branches:
      - master

jobs:
  build-uiw-admin:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - run: npm install
    - run: npm run publish

